# Secret to change default password for super-user
---
apiVersion: v1
kind: Secret
metadata:
  name: quay-superuser
  namespace: user21
type: Opaque
stringData:
  superuser-username: quay
  superuser-password: openshift
  superuser-email: quay@redhat.com
---
apiVersion: v1
kind: Secret
metadata:
  name: quay-database-credential
  namespace: user21
type: Opaque
stringData:
  database-username: quay
  database-password: openshift
  database-root-password: openshift
  database-name: quay-enterprise
---
apiVersion: v1
kind: Secret
metadata:
  name: quay-config-app
  namespace: user21
type: Opaque
stringData:
  config-app-password: openshift
---
apiVersion: v1
kind: Secret
metadata:
  name: quay-redis-password
  namespace: user21
type: Opaque
stringData:
  password: openshift