apiVersion: redhatcop.redhat.io/v1alpha1
kind: QuayEcosystem
metadata:
  name: quayecosystem
  namespace: quay-enterprise
spec:
  quay:
    enableRepoMirroring: true
    keepConfigDeployment: true
    superuserCredentialsSecretName: quay-superuser
    externalAccess:
      hostname: quay.apps-crc.testing
      tls:
        termination: edge
      type: Route
    database:
      volumeSize: 10Gi
    imagePullSecretName: dummy-pull-secret
    registryStorage:
      persistentVolumeAccessModes:
        - ReadWriteOnce
      persistentVolumeSize: 10Gi
    securityContext:
      fsGroup: 1001
  clair:
    enabled: true
    imagePullSecretName: dummy-pull-secret